#!/usr/bin/env bash
# Pi Signage installer — run ON the Raspberry Pi (Raspberry Pi OS Bookworm, Desktop image)
#   bash install.sh
# Idempotent: safe to re-run.
set -euo pipefail

USER_NAME="${SUDO_USER:-$USER}"
HOME_DIR="$(getent passwd "$USER_NAME" | cut -d: -f6)"
APP_DIR="$HOME_DIR/pi-signage"
AGENT_DIR="$APP_DIR/agent"

echo "==> Installing for user: $USER_NAME ($HOME_DIR)"

# ---------------------------------------------------------------- packages
sudo apt-get update
# Trixie ships the binary as `chromium`; Bookworm as `chromium-browser`. Install
# whichever exists (kiosk.sh auto-detects the binary name at runtime).
sudo apt-get install -y python3-venv chromium unzip wayvnc openssh-client || \
  sudo apt-get install -y python3-venv chromium-browser unzip wayvnc openssh-client

# ---------------------------------------------------------------- agent
if [ ! -d "$AGENT_DIR" ]; then
  echo "ERROR: copy the repo to $APP_DIR first (agent/ must exist)"; exit 1
fi

python3 -m venv "$AGENT_DIR/.venv"
"$AGENT_DIR/.venv/bin/pip" install --upgrade pip
"$AGENT_DIR/.venv/bin/pip" install -r "$AGENT_DIR/requirements.txt"

# ---------------------------------------------------------------- agent service
USER_UID="$(id -u "$USER_NAME")"
# XDG_RUNTIME_DIR + the session bus let the agent drive the user-session kiosk
# service (systemctl --user) so the control app can stop/start the kiosk.
sudo tee /etc/systemd/system/signage-agent.service >/dev/null <<EOF
[Unit]
Description=Pi Signage Agent
After=network-online.target
Wants=network-online.target

[Service]
User=$USER_NAME
WorkingDirectory=$AGENT_DIR
Environment=SIGNAGE_PORT=8080
Environment=XDG_RUNTIME_DIR=/run/user/$USER_UID
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USER_UID/bus
ExecStart=$AGENT_DIR/.venv/bin/python main.py
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now signage-agent.service

# ---------------------------------------------------------------- kiosk launcher
mkdir -p "$APP_DIR"

# h264ify: forces YouTube (and other HTML5 video) to H.264 so the Pi 4 HARDWARE-
# decodes it. YouTube's default VP9 has no HW decoder on the Pi 4 -> software ->
# stutter. Downloaded from the Chrome Web Store, unpacked for --load-extension.
H264DIR="$HOME_DIR/h264ify"
rm -rf "$H264DIR"; mkdir -p "$H264DIR"
if curl -sL -o /tmp/h264ify.crx "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=120.0&x=id%3Daleakchihdccplidncghkekgioiakgal%26installsource%3Dondemand%26uc"; then
  python3 -c "d=open('/tmp/h264ify.crx','rb').read(); i=d.find(b'PK\x03\x04'); open('/tmp/h264ify.zip','wb').write(d[i:])" \
    && unzip -oq /tmp/h264ify.zip -d "$H264DIR" && rm -rf "$H264DIR/_metadata"
fi

# First write only — the agent rewrites kiosk.sh at startup whenever its
# bundled template (KIOSK_SH in agent/main.py) changes, so keep the two in sync.
cat > "$APP_DIR/kiosk.sh" <<'EOF'
#!/usr/bin/env bash
# Wait for the agent, then run Chromium fullscreen on the signage page forever.
# AUTO-GENERATED by the agent at startup — local edits are overwritten.
CHROME="$(command -v chromium || command -v chromium-browser)"   # Trixie=chromium, Bookworm=chromium-browser
PROFILE="$HOME/.config/pisignage-kiosk"                          # dedicated profile (no stray tabs/logins)
EXTFLAG=""; [ -f "$HOME/h264ify/manifest.json" ] && EXTFLAG="--load-extension=$HOME/h264ify"
until curl -sf http://localhost:8080/api/status >/dev/null; do sleep 1; done
while true; do
  # never let a saved session/tab take over — always open the signage page
  rm -f "$PROFILE"/Default/Current\ Session "$PROFILE"/Default/Current\ Tabs \
        "$PROFILE"/Default/Last\ Session "$PROFILE"/Default/Last\ Tabs 2>/dev/null
  # --password-store=basic: without it Chromium asks GNOME keyring to unlock,
  # which pops "Choose a password for the new keyring" over the desktop the
  # first time someone signs into a site (e.g. Spotify) via remote control
  "$CHROME" --kiosk "http://localhost:8080/" --user-data-dir="$PROFILE" \
    --noerrdialogs --disable-infobars --disable-session-crashed-bubble --no-first-run \
    --password-store=basic \
    --disable-features=Translate --autoplay-policy=no-user-gesture-required \
    --check-for-update-interval=31536000 --overscroll-history-navigation=0 \
    --enable-gpu-rasterization --ignore-gpu-blocklist \
    --disk-cache-size=104857600 $EXTFLAG   # 100MB cache cap: protect the SD card
  sleep 2   # if Chromium ever crashes, relaunch it
done
EOF
chmod +x "$APP_DIR/kiosk.sh"

# ---- zram: compressed swap for the 2GB Pi (faster + saves SD wear vs SD swap) ----
sudo apt-get install -y zram-tools
printf 'ALGO=zstd\nPERCENT=150\n' | sudo tee /etc/default/zramswap >/dev/null
sudo systemctl enable --now zramswap.service 2>/dev/null || true
sudo systemctl restart zramswap.service 2>/dev/null || true

# ---- kiosk as a systemd USER service, so the app can stop/start it on demand ----
# (stopping it exposes the local Pi desktop; starting it brings signage back)
mkdir -p "$HOME_DIR/.config/systemd/user"
cat > "$HOME_DIR/.config/systemd/user/pisignage-kiosk.service" <<EOF
[Unit]
Description=PiSignage Chromium kiosk
After=graphical-session.target
PartOf=graphical-session.target

[Service]
# full desktop-session env so Chromium can actually render (missing these = a
# white screen: it launches but can't compose to the Wayland surface)
Environment=WAYLAND_DISPLAY=wayland-0
Environment=XDG_RUNTIME_DIR=/run/user/$USER_UID
Environment=XDG_CURRENT_DESKTOP=labwc:wlroots
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USER_UID/bus
ExecStart=$APP_DIR/kiosk.sh
# make sure stopping the kiosk really clears Chromium off the screen
ExecStopPost=-/usr/bin/pkill -f chromium
Restart=always
RestartSec=2

[Install]
WantedBy=graphical-session.target
EOF
# ---- daily kiosk restart (04:00): clears renderer crashes ("Aw, Snap" keeps
# the process alive so the crash-relaunch loop never fires) and memory creep ----
cat > "$HOME_DIR/.config/systemd/user/pisignage-kiosk-restart.service" <<EOF
[Unit]
Description=Restart PiSignage kiosk (daily hygiene)

[Service]
Type=oneshot
ExecStart=/usr/bin/systemctl --user try-restart pisignage-kiosk.service
EOF
cat > "$HOME_DIR/.config/systemd/user/pisignage-kiosk-restart.timer" <<EOF
[Unit]
Description=Daily PiSignage kiosk restart

[Timer]
OnCalendar=*-*-* 04:00:00

[Install]
WantedBy=timers.target
EOF
# enable by symlink — works even when the user bus isn't up during install
mkdir -p "$HOME_DIR/.config/systemd/user/timers.target.wants"
ln -sf ../pisignage-kiosk-restart.timer \
  "$HOME_DIR/.config/systemd/user/timers.target.wants/pisignage-kiosk-restart.timer"

# keep the user manager alive so the agent can reach it (systemctl --user)
sudo loginctl enable-linger "$USER_NAME" || true

# ---------------------------------------------------------------- autostart (labwc/wayfire)
# Start the kiosk via its user service, importing the compositor env first so
# Chromium finds the Wayland display.
mkdir -p "$HOME_DIR/.config/labwc" "$HOME_DIR/.config/autostart"
KIOSK_START='systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR XDG_CURRENT_DESKTOP; systemctl --user start pisignage-kiosk.service'

# remove any old direct-launch line, then add the service-start line
sed -i '/kiosk\.sh/d' "$HOME_DIR/.config/labwc/autostart" 2>/dev/null || true
grep -q pisignage-kiosk "$HOME_DIR/.config/labwc/autostart" 2>/dev/null || \
  echo "$KIOSK_START" >> "$HOME_DIR/.config/labwc/autostart"

cat > "$HOME_DIR/.config/autostart/signage-kiosk.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Signage Kiosk
Exec=sh -c "$KIOSK_START"
X-GNOME-Autostart-enabled=true
EOF

# ---------------------------------------------------------------- polish
# cap the journal so logs can never fill the SD card
sudo mkdir -p /etc/systemd/journald.conf.d
printf '[Journal]\nSystemMaxUse=64M\n' | sudo tee /etc/systemd/journald.conf.d/pisignage.conf >/dev/null
sudo systemctl restart systemd-journald || true

# hardware watchdog: if the kernel ever hard-hangs, the Pi reboots itself in
# ~15s instead of showing a frozen sign until someone pulls the plug
sudo mkdir -p /etc/systemd/system.conf.d
printf '[Manager]\nRuntimeWatchdogSec=15\n' | sudo tee /etc/systemd/system.conf.d/pisignage-watchdog.conf >/dev/null

# never blank the screen
sudo raspi-config nonint do_blanking 1 || true
# boot to desktop with autologin (kiosk needs a session)
sudo raspi-config nonint do_boot_behaviour B4 || true

echo ""
echo "==> Done. Reboot to start the kiosk:  sudo reboot"
echo "    Agent API:  http://$(hostname -I | awk '{print $1}'):8080/api/status"
